[workspace]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
name = "linear-algebra"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
python = ">=3.14.2,<3.15"

[pypi-dependencies]
numpy = "*"
matplotlib = "*"
sympy = "*"
scipy = "*"
scikit-learn = "*"
networkx = "*"
scikit-image = "*"
jupyter = "*"
